adicionando comando de compilacao para rust em mk e kk

diff --git a/kk b/kk
--- a/kk
+++ b/kk
@@ -1,7 +1,7 @@
 #!/usr/bin/bash
 
 if [[ $# -eq 0 ]]; then
-    echo "Missing parameters"
+    echo "Missing parameters" >&2
     exit 1
 fi
 
@@ -10,10 +10,19 @@ if [[ $# -gt 1 ]]; then
     exit
 
 elif [[ -f $1.c ]]; then
-        gcc -Wall -Wextra -Wpedantic -O2 -std=gnu23 -o "$1" "$1.c" && ./"$1"
-        exit 
+    gcc -Wall -Wextra -Wpedantic -O2 -std=gnu23 -o "$1" "$1.c" && ./"$1"
+    exit 
 
 elif [[ -f $1.cpp ]]; then
-        g++ -Wall -Wextra -Wpedantic -O2 -std=c++23 -o "$1" "$1.cpp" && ./"$1"
-        exit
+    g++ -Wall -Wextra -Wpedantic -O2 -std=c++23 -o "$1" "$1.cpp" && ./"$1"
+    exit
+
+elif [[ -f $1.rs ]]; then
+    rustc "$1.rs" && ./"$1"
+    exit
+
+elif [[ ! -f $1.c ]] && [[ ! -f $1.cpp ]]; then
+    echo "Arquivos nao encontrados" >&2
+    exit 1
+
 fi
